#开发环境DB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dash
    username: dash
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      port: 6379
      host: localhost
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true