INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (1, '计算机', '数据结构', '数据结构是一门计算机学科');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (2, '计算机', '计算机网络', '计算机网络是一门是计算机学科');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (3, '娱乐', '三生三世十里桃花', '是一个热门小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (5, '小说', '小李飞刀5', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (6, '小说', '小李飞刀6', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (8, '计算机', '计算机原理', '撒大苏打盛大的');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (13, '小说', '神雕侠侣', '经典小说神雕侠侣');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (14, '小说', '小李飞刀', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (16, 'impl test', 'impl test', 'impl test');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (17, '小说', '神雕侠侣', '经典小说神雕侠侣');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (18, '小说', '小李飞刀', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (19, '小说', '小李飞刀7', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (20, 'impl test', 'impl test', 'impl test');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (21, '小说', '小李飞刀', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (22, '小说', '小李飞刀7', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (24, 'impl test', 'impl test', 'impl test');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (25, '小说', '神雕侠侣', '经典小说神雕侠侣');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (26, '小说', '小李飞刀', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (27, '小说', '小李飞刀7', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (28, 'impl test', 'impl test', 'impl test');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (29, '小说', '神雕侠侣', '经典小说神雕侠侣');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (30, '小说', '小李飞刀', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (31, '小说', '小李飞刀7', '武打小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (32, 'impl test', 'impl test', 'impl test');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (33, '小说', '仙剑奇侠传', '武侠小说');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (36, '小说', '神雕侠侣', '经典小说神雕侠侣');
INSERT INTO `tbl_book` (`id`, `type`, `name`, `description`) VALUES (37, '2', '2', '2');
